learning_rate: 0.000001
batch_size: 256
epochs: 100
sim_weight: 1.0
reg_weight: 1.0
train_backbone: True
use_augmentation: True
use_similarity_augmentation: False
backbone_checkpoint: null
early_stopping_patience: 10
optimizer: lion
max_workers: 0
use_float16: True
