basepath: "data/db2/"
metadata: "MFD_metadatas.csv"
images: "Images"
train_max_age: 30
val_max_age: 30
train_min_quality: 0
val_min_quality: 1
train_faceview: 1
val_faceview: 1
dob_certain_only: False
max_dob_error: 15
in_memory: True
train_ratio: 0.8
sex: null
similarity_threshold:
  - factor: 0.05
  - min_days: 5
normalize_y: False
im_size: 224
